FROM raspbian-bullseye

RUN apt-get update
RUN apt-get -y install build-essential unzip git gdb curl cmake libx11-dev libglu1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev zlib1g-dev libasound2-dev libgtk2.0-dev libgtk-3-dev libjack-jackd2-dev jq zstd libpulse-dev zip wget vim nasm yasm libmp3lame-dev premake4 libxt-dev libudev-dev libstdc++-7-dev libavcodec-dev
